#!/usr/bin/env python

import sys

from pyrosetta import *
from pyrosetta.rosetta import *

init(" ".join(sys.argv[1:]))

silent_files = utility.vector1_utility_file_FileName()
for silent_file in basic.options.get_file_vector_option("in:file:silent"):
    silent_files.append(utility.file.FileName(silent_file))

input_stream = core.import_pose.pose_stream.SilentFilePoseInputStream(silent_files)


pose = core.pose.Pose()

while input_stream.has_another_pose():
    input_stream.fill_pose(pose)

    pose.dump_pdb(core.pose.tag_from_pose(pose) + ".pdb")