#!/usr/bin/env python

import sys

from pyrosetta import *
from pyrosetta.rosetta import *
from pyrosetta.rosetta.protocols.jd2 import *

init(" ".join(sys.argv[1:]))

jobout = SilentFileJobOutputter()
jobout.set_write_no_structures()
jobout.set_write_separate_scorefile(True)


JobDistributor.get_instance().set_job_outputter( JobDistributorFactory.create_job_outputter( jobout ));

JobDistributor.get_instance().go( protocols.simple_moves.ScoreMover() );